drop table Company cascade constraints;
drop table Keyword cascade constraints;
drop table Level cascade constraints;
drop table Product cascade constraints;
drop table app_user cascade constraints;
drop table company_keyword cascade constraints;
drop table product_keyword cascade constraints;
drop table role cascade constraints;
drop table user_role cascade constraints;
drop sequence hibernate_sequence;
