//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldTradeNaming.Web.goldtrade_db_admin {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class goldtrade_db_adminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal goldtrade_db_adminRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldTradeNaming.Web.goldtrade_db_admin.goldtrade_db_adminRes", typeof(goldtrade_db_adminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string strAddSuccess {
            get {
                return ResourceManager.GetString("strAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定不修改就关闭吗？ 的本地化字符串。
        /// </summary>
        internal static string strConfirmColse {
            get {
                return ResourceManager.GetString("strConfirmColse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string strEditSuccess {
            get {
                return ResourceManager.GetString("strEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员姓名已存在，请检查！ 的本地化字符串。
        /// </summary>
        internal static string strhasExists {
            get {
                return ResourceManager.GetString("strhasExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IA100唯一ID不正确，请检查！ 的本地化字符串。
        /// </summary>
        internal static string strIA100GUID_Error {
            get {
                return ResourceManager.GetString("strIA100GUID_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此IA100唯一ID已被使用，请检查！ 的本地化字符串。
        /// </summary>
        internal static string strIA100GUID_InUse {
            get {
                return ResourceManager.GetString("strIA100GUID_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IA100唯一ID未注册，请先注册！ 的本地化字符串。
        /// </summary>
        internal static string strIA100NotReg {
            get {
                return ResourceManager.GetString("strIA100NotReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录出错，请重新操作或联系管理员! 的本地化字符串。
        /// </summary>
        internal static string strLoginError {
            get {
                return ResourceManager.GetString("strLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有权限登录本系统！\\n请重新登录或与管理员联系 的本地化字符串。
        /// </summary>
        internal static string strNoRigthIntoSystem {
            get {
                return ResourceManager.GetString("strNoRigthIntoSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加过程中发生错误，操作已经终止。 的本地化字符串。
        /// </summary>
        internal static string strSystemError {
            get {
                return ResourceManager.GetString("strSystemError", resourceCulture);
            }
        }
    }
}
